server:
  port: 56020

spring:
  application:
    name: nacos-restful-consumer
  cloud:
    nacos:
      discovery:
        server‐addr: 127.0.0.1:8848

nacos-restful-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule